/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/base/Button.vue')['default']
    Card: typeof import('./src/components/layout/Card.vue')['default']
    CardActions: typeof import('./src/components/layout/CardActions.vue')['default']
    CardBottomActions: typeof import('./src/components/layout/CardBottomActions.vue')['default']
    CardHeader: typeof import('./src/components/layout/CardHeader.vue')['default']
    CardKPI: typeof import('./src/components/dashboard/CardKPI.vue')['default']
    CardTransitionWrapper: typeof import('./src/components/layout/CardTransitionWrapper.vue')['default']
    ConfirmDialog: typeof import('./src/components/overlay/ConfirmDialog.vue')['default']
    ContentContainer: typeof import('./src/components/layout/ContentContainer.vue')['default']
    ContextMenu: typeof import('./src/components/table/ContextMenu.vue')['default']
    EditableField: typeof import('./src/components/layout/section/EditableField.vue')['default']
    EditableSectionCard: typeof import('./src/components/layout/section/EditableSectionCard.vue')['default']
    ErrorMessage: typeof import('./src/components/base/ErrorMessage.vue')['default']
    FileUpload: typeof import('./src/components/base/FileUpload.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Form: typeof import('./src/components/base/Form.vue')['default']
    FormField: typeof import('./src/components/base/FormField.vue')['default']
    IconFileTypeXlsx: typeof import('./src/components/icons/IconFileTypeXlsx.vue')['default']
    InputText: typeof import('./src/components/base/InputText.vue')['default']
    LinkifiedText: typeof import('./src/components/base/LinkifiedText.vue')['default']
    MainMenu: typeof import('./src/components/menu/MainMenu.vue')['default']
    MenuSection: typeof import('./src/components/menu/MenuSection.vue')['default']
    MenuSectionItem: typeof import('./src/components/menu/MenuSectionItem.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
    PaginationButton: typeof import('./src/components/table/PaginationButton.vue')['default']
    ParcelLocationDetails: typeof import('./src/components/parcels/ParcelLocationDetails.vue')['default']
    PopupMenu: typeof import('./src/components/menu/PopupMenu.vue')['default']
    PopupTransitionWrapper: typeof import('./src/components/menu/PopupTransitionWrapper.vue')['default']
    Price: typeof import('./src/components/base/Price.vue')['default']
    ProfileHeader: typeof import('./src/components/layout/ProfileHeader.vue')['default']
    RadioOptionCard: typeof import('./src/components/base/RadioOptionCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SmallCardKPI: typeof import('./src/components/dashboard/SmallCardKPI.vue')['default']
    SortIcon: typeof import('./src/components/table/SortIcon.vue')['default']
    SubText: typeof import('./src/components/base/SubText.vue')['default']
    Table: typeof import('./src/components/table/Table.vue')['default']
    Tag: typeof import('./src/components/base/Tag.vue')['default']
    Toast: typeof import('./src/components/overlay/Toast.vue')['default']
  }
}
